// apps/admin-web/src/components/admin/status-badge.tsx
const statusMeta: Record<string, { label: string; className: string }> = {
  assigned: { label: "待出车", className: "status neutral" },
  in_progress: { label: "进行中", className: "status info" },
  submitted: { label: "已提交", className: "status warning" },
  under_review: { label: "审核中", className: "status warning" },
  completed: { label: "已完成", className: "status success" },
  returned: { label: "已退回", className: "status danger" },
  cancelled: { label: "已撤销", className: "status danger" },
  available: { label: "可用", className: "status success" },
  idle: { label: "空闲中", className: "status success" },
  transporting: { label: "运输中", className: "status info" },
  maintenance: { label: "维修中", className: "status warning" },
  disabled: { label: "停用", className: "status danger" },
  active: { label: "在职", className: "status success" },
  enabled: { label: "启用", className: "status success" },
};

export function statusLabel(status: string): string {
  return statusMeta[status]?.label ?? status;
}

export function StatusBadge({ status }: { status: string }) {
  const meta = statusMeta[status] ?? { label: status, className: "status neutral" };

  return <span className={meta.className}>{meta.label}</span>;
}

// apps/driver-uni/src/components/StatusBadge.vue
<template>
  <text :class="['status-badge', tone]">{{ label }}</text>
</template>

<script setup lang="ts">
import { computed } from "vue";

const props = defineProps<{ status: string }>();

const labels: Record<string, string> = {
  assigned: "待出车",
  in_progress: "进行中",
  submitted: "已提交",
  under_review: "审核中",
  completed: "已完成",
  returned: "已退回",
  cancelled: "已撤销",
};

const label = computed(() => labels[props.status] ?? props.status);

const tone = computed(() => {
  if (props.status === "in_progress" || label.value === "进行中") return "accent";
  if (props.status === "submitted" || props.status === "under_review") return "warning";
  if (label.value === "已提交" || label.value === "审核中") return "warning";
  if (props.status === "completed" || label.value === "已完成") return "success";
  if (props.status === "returned" || props.status === "cancelled" || label.value === "已退回" || label.value === "已撤销") return "danger";
  return "neutral";
});
</script>

<style scoped>
.status-badge {
  display: inline-flex;
  flex: 0 0 auto;
  align-items: center;
  min-height: 26px;
  padding: 4px 12px;
  border-radius: 999px;
  font-size: 12px;
  font-weight: 600;
  line-height: 16px;
  white-space: nowrap;
}

.neutral {
  background: #eef4ff;
  color: var(--driver-primary);
}

.accent {
  background: rgba(255, 180, 84, 0.18);
  color: #996014;
}

.warning {
  background: rgba(18, 98, 184, 0.12);
  color: var(--driver-primary-2);
}

.success {
  background: rgba(31, 143, 97, 0.12);
  color: var(--driver-green);
}

.danger {
  background: rgba(194, 59, 54, 0.12);
  color: var(--driver-red);
}
</style>
